Settings-Fragment as replacement for ThreeDot-Menu implemented
seemoo-lab/fitness-app pull request #56
Opened 2018-08-11 07:58 UTC by Tobis93

Closes #14.

2018-08-13 12:56 UTC, stekreis approved these changes

2018-08-13 16:24 UTC, anykeyjunkie requested changes

2018-08-13 16:24 UTC, anykeyjunkie commented on app/src/main/java/seemoo/fitbit/fragments/prefFragment.java
> +public class prefFragment extends PreferenceFragmentCompat {
Class names capitalized

2018-08-13 16:24 UTC, anykeyjunkie commented on app/src/main/java/seemoo/fitbit/fragments/prefFragment.java
> +        final String setting1 = getResources().getString(R.string.settings_workactivity_1);
can we use more meaningful variable names instead of the numering setting1, setting2 etc? maybe settingAdditionalRawOutput etc

2018-08-13 16:24 UTC, anykeyjunkie commented on app/src/main/java/seemoo/fitbit/fragments/prefFragment.java
> +        CheckBoxPreference checkBox3 = (CheckBoxPreference) findPreference(setting3);
same for the checkbox names...maybe dumpFilesCheckbox

2018-08-13 16:24 UTC, anykeyjunkie commented on app/src/main/res/xml/preferences.xml
> +<PreferenceScreen
font size is too big on my device: second setting is displayed as "additional alarm informati...". could you decrease the font size?

2018-08-14 18:56 UTC, Tobis93 commented on app/src/main/java/seemoo/fitbit/fragments/prefFragment.java
> +public class prefFragment extends PreferenceFragmentCompat {
Done

2018-08-14 18:56 UTC, Tobis93 commented on app/src/main/java/seemoo/fitbit/fragments/prefFragment.java
> +        final String setting1 = getResources().getString(R.string.settings_workactivity_1);
Adjusted the Variable-Names

2018-08-14 18:57 UTC, Tobis93 commented on app/src/main/java/seemoo/fitbit/fragments/prefFragment.java
> +        CheckBoxPreference checkBox3 = (CheckBoxPreference) findPreference(setting3);
Adjusted the Variable-Names

2018-08-14 18:57 UTC, Tobis93 commented on app/src/main/res/xml/preferences.xml
> +<PreferenceScreen
Changed Theme of the Fragment. Please retest and give me feedback if it looks better now

2018-08-15 09:36 UTC, anykeyjunkie approved these changes

2018-08-15 09:36 UTC, merged